name: Cypress Test
on:

  # Run on any commit to the #master branch
  push:
    branches: [master]

  # Run on pull requests into the #master branch

  pull_request:
    branches: [master]

  # Allows user to trigger the workflow from GitHub's web UI
  workflow_dispatch:

jobs:
  install-ab:
    runs-on: ubuntu-latest
    steps:

      # Setup
      - name: Install AppBuilder
        run: docker swarm init && npx digi-serve/ab-cli install ab --stack=ab --port=80 --db.expose=false --db.password=root --db.encryption=false --tag=develop --nginx.enable=true --ssl.none --bot.enable=false --smtp.enable=false --tenant.username=admin --tenant.password=admin --tenant.email=neo@thematrix.com

      # Up
      - name: Bring up AppBuilder
        run: ./ab/UP.sh -q -t && ls ./ab -la
        
  run-test:
    needs: install-ab
    runs-on: ubuntu-latest
    steps:
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./ab
          project: ./test/e2e
          config: baseUrl=http://localhost:8080

          # Wait for the site to be ready
          wait-on: "http://localhost:8080"
          wait-on-timeout: 300

          # We need to set the stack name as an environment variable for
          # the test reset script.
          env: stack=ab
